#-------------------------------------------------------------------------
#
# Makefile--
#    Makefile for piggyback
#
# IDENTIFICATION
#    src/backend/piggyback/Makefile
#
#-------------------------------------------------------------------------

subdir = src/backend/piggyback
top_builddir = ../../..
include $(top_builddir)/src/Makefile.global

OBJS = piggyback.o

include $(top_srcdir)/src/backend/common.mk

piggyback.o: piggyback.c
